DROP TABLE IF EXISTS a;
DROP TABLE IF EXISTS b;
DROP TABLE IF EXISTS c;
DROP TABLE IF EXISTS d;

CREATE TABLE a (
	S INT NOT NULL AUTO_INCREMENT,
    V INT NOT NULL,
    PRIMARY KEY (S)
);
CREATE TABLE b (
	S INT NOT NULL AUTO_INCREMENT,
    V INT NOT NULL,
    PRIMARY KEY (S)
);
CREATE TABLE c (
	S INT NOT NULL AUTO_INCREMENT,
    V INT NOT NULL,
    PRIMARY KEY (S)
);
CREATE TABLE d (
	S INT NOT NULL AUTO_INCREMENT,
    V INT NOT NULL,
    PRIMARY KEY (S)
);
