CREATE TABLE A (
	S INT NOT NULL AUTO_INCREMENT,
    V INT NOT NULL,
    PRIMARY KEY (S)
);
CREATE TABLE B (
	S INT NOT NULL AUTO_INCREMENT,
    V INT NOT NULL,
    PRIMARY KEY (S)
);
CREATE TABLE C (
	S INT NOT NULL AUTO_INCREMENT,
    V INT NOT NULL,
    PRIMARY KEY (S)
);
CREATE TABLE D (
	S INT NOT NULL AUTO_INCREMENT,
    V INT NOT NULL,
    PRIMARY KEY (S)
);

DROP PROCEDURE IF EXISTS LoadTestData_A;
CREATE PROCEDURE LoadTestData_A()
BEGIN
	DECLARE v_max INT UNSIGNED DEFAULT 10;
	DECLARE v_counter INT UNSIGNED DEFAULT 0;

	TRUNCATE TABLE A;
	START TRANSACTION;
	WHILE v_counter < v_max DO
		INSERT INTO A (v) VALUES ( floor(0 + (rand() * 10)) );
        SET v_counter=v_counter+1;
	END WHILE;
	COMMIT;
END;

DROP PROCEDURE IF EXISTS LoadTestData_B;
CREATE PROCEDURE LoadTestData_B()
BEGIN
	DECLARE v_max INT UNSIGNED DEFAULT 50;
	DECLARE v_counter INT UNSIGNED DEFAULT 0;

	TRUNCATE TABLE B;
	START TRANSACTION;
	WHILE v_counter < v_max DO
		INSERT INTO B (V) VALUES ( floor(0 + (rand() * 50)) );
        SET v_counter=v_counter+1;
	END WHILE;
	COMMIT;
END;

DROP PROCEDURE IF EXISTS LoadTestData_C;
CREATE PROCEDURE LoadTestData_C()
BEGIN
	DECLARE v_max INT UNSIGNED DEFAULT 100;
	DECLARE v_counter INT UNSIGNED DEFAULT 0;

	TRUNCATE TABLE C;
	START TRANSACTION;
	WHILE v_counter < v_max DO
		INSERT INTO C (V) VALUES ( floor(0 + (rand() * 100)) );
        SET v_counter=v_counter+1;
	END WHILE;
	COMMIT;
END;

DROP PROCEDURE IF EXISTS LoadTestData_D;
CREATE PROCEDURE LoadTestData_D()
BEGIN
	DECLARE v_max INT UNSIGNED DEFAULT 500;
	DECLARE v_counter INT UNSIGNED DEFAULT 0;

	TRUNCATE TABLE D;
	START TRANSACTION;
	WHILE v_counter < v_max DO
		INSERT INTO D (V) VALUES ( floor(0 + (rand() * 1000)) );
        SET v_counter=v_counter+1;
	END WHILE;
	COMMIT;
END;

CALL LoadTestData_A();
CALL LoadTestData_B();
CALL LoadTestData_C();
CALL LoadTestData_D();